
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author capps
 */
public class HealthProfileGUI extends javax.swing.JFrame {

    /**
     * Creates new form HealthProfileGUI
     */
    public HealthProfileGUI() {
        initComponents();
        
        // center the form and other edits like background 
        this.setLocationRelativeTo(null);
        //needs to import color 
        this.getContentPane().setBackground(Color.gray);
//this.setBackground(background color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblFeet = new javax.swing.JLabel();
        lblInches = new javax.swing.JLabel();
        lblBMI = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        lblMaxHR = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtFeet = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtInches = new javax.swing.JTextField();
        txtBMI = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtMaxHR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Health Profile App");
        setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblName.setText("Name:");

        lblAge.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAge.setText("Age:");

        lblWeight.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblWeight.setText("Weight:");

        lblFeet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFeet.setText("Height-Feet:");

        lblInches.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInches.setText("Height-Inches:");

        lblBMI.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBMI.setText("BMI:");

        btnDisplay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCategory.setText("Category:");

        lblMaxHR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMaxHR.setText("Max Heart Rate:");

        txtWeight.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtFeet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtAge.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtInches.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtBMI.setEditable(false);
        txtBMI.setBackground(new java.awt.Color(255, 255, 255));
        txtBMI.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtCategory.setEditable(false);
        txtCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtCategory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtMaxHR.setEditable(false);
        txtMaxHR.setBackground(new java.awt.Color(255, 255, 255));
        txtMaxHR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblInches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaxHR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBMI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFeet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategory)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(txtWeight)
                            .addComponent(txtFeet)
                            .addComponent(txtAge)
                            .addComponent(txtInches))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBMI, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(txtMaxHR))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFeet)
                    .addComponent(txtFeet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInches)
                    .addComponent(txtInches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBMI)
                    .addComponent(txtBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxHR)
                    .addComponent(txtMaxHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        //shows a window with Works!
        //JOptionPane.showMessageDialog(this,"Works!");
        
        //Verify the text fields
        if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Name is Required", "Error", JOptionPane.ERROR_MESSAGE);
            txtName.requestFocus();
            return; //stops the method from running
        }
        if(txtAge.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Age is Required", "Error", JOptionPane.ERROR_MESSAGE);
            txtAge.requestFocus();
            return; //stops the method from running
        } 
        if(txtWeight.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Weight is Required", "Error", JOptionPane.ERROR_MESSAGE);
            txtWeight.requestFocus();
            return; //stops the method from running
        }
        if(txtFeet.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Height-Feet is Required", "Error", JOptionPane.ERROR_MESSAGE);
            txtFeet.requestFocus();
            return; //stops the method from running
        }
        if(txtInches.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Height-Inches is Required", "Error", JOptionPane.ERROR_MESSAGE);
            txtInches.requestFocus();
            return; //stops the method from running
        }
        //Get Data form Text fields
        String name = txtName.getText();
        int age = Integer.parseInt(txtAge.getText());
        double weight = Double.parseDouble(txtWeight.getText());
        int feet = Integer.parseInt(txtFeet.getText());
        double inches = Double.parseDouble(txtInches.getText());
        //Create health profile
        HealthProfile profile = new HealthProfile(name, age, weight, feet, inches);
        //Show output
        double bmi = profile.calculateBMI();
        DecimalFormat fmt = new DecimalFormat("0.0");
        txtBMI.setText(fmt.format(bmi)); // formatting makes it into a string
        txtCategory.setText(profile.calculateCategory());
        txtMaxHR.setText("" + profile.calculateMaxHR()); // ' "" + ' Also makes a string
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        //Clear All fields
        txtName.setText("");
        txtAge.setText("");
        txtWeight.setText("");
        txtFeet.setText("");
        txtInches.setText("");
        txtBMI.setText("");
        txtCategory.setText("");
        txtMaxHR.setText("");
        txtName.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthProfileGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBMI;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblFeet;
    private javax.swing.JLabel lblInches;
    private javax.swing.JLabel lblMaxHR;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBMI;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtFeet;
    private javax.swing.JTextField txtInches;
    private javax.swing.JTextField txtMaxHR;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
